### PR TITLE
Feat: multi browser handling

### PR DESCRIPTION
**Pull request by seopei**
- added two functions to add/remove a screenshot browser instance
- added a typings file in order to user this plugin in angular 2 projects

### CODE REVIEW

**Comment by azachar** [comment]
Hello, 

Thank you for your PR, could you please squish it and rebase it on the feat-ascii-image?

Also it would be great, if you could provide some tests for your modifications. 

Cheers,
Andrej

**Comment by azachar** [comment]
Hello, 
thank you for your PR. 

Could you please explain your motivation for your changes and what are the benefits of them?

Thanks.

**Comment by seopei** [comment]
hello,
I am sorry for my late answer!

My motivation behind this PR is that I was not able to take screenshots with multi browser instances at my angular 2 app. So I made some helper methods and a typings file and now everything is working fine.

now you can fork a new browser instance and add them to your screenshot browsers with something like that
`var firstBrowser = protractorUtils.addScreenshotBrowser('first');`
instead of that
`var firstBrowser  = browser.forkNewDriverInstance();`
`global.screenshotBrowsers['first'] = firstBrowser;`

and to remove it
`protractorUtils.removeScreenshotBrowser('first');`

and if you want to skip image to ascii function
`var secondBrowser = protractorUtils.addScreenshotBrowser('second', true);`

I updated multi-browser-instance-test.js and console-error-test.js.

cheers, Sebastian

**Comment by azachar** [comment]
Dear @seopei 

As far as I know, you do not need to do any plugin modification to support Angular 2 (https://github.com/azachar/protractor-screenshoter-plugin/issues/39#issuecomment-312257878)

Second, a wrapper method for forking a browser with just one addition a browser name and restricting the access to other params for forking seems to a bit overhead.

I think, if you test a multi-browser app, like a chat app, the best practice is beside PO objects create a class that wraps access to the browser instance, there you can add such methods with your control of forking and screenshoter naming.

So for now, I am closing this PR. Anyway, thank you once again for your work!

**Pull request closed without merging**
