### PR TITLE
Add `suites` parameter to failTestOnErrorLog

### PR DESCRIPTION
**Pull request by joaomqcunha**
**Motivation:** Some `suites`, like the ones with mocked data we don't want the tests to fail because of browser's console errors.

**Changes:** This merge-requests adds the ability to specify which `suites` (protractor.config.suites) do we want to failTestOnErrorLog.

### CODE REVIEW

**Comment by azachar** [comment]
Dear @joaomqcunha, 

it looks interesting, could you please provide tests to cover this functionality?

Have a look at the existing one, create a new config with your options and run tests against it.

Thank you!

Cheers,
Andrej

**Comment by joaomqcunha** [comment]
Tests completed. @azachar: Can you please review it again?

**Comment by azachar** [comment]
Dear @joaomqcunha, 
Thank you for your contribution. It looks promising.

**Comment by joaomqcunha** [comment]
Hi @azachar, you told me to create test scenarios and I've already done that. Is that something else missing?

**Comment by azachar** [comment]
Dear @joaomqcunha,

All is done, except one method to be renamed - isAValidSuite. Do you see my review comment in your code? If not, here it is again:

I would call it isSuiteSelected or isASuiteToCheck or isSuiteCheckEnabled or isSuiteEnabled

Once, this is renamed, I will squish+merge it.

Cheers, 
Andrej

**Comment by joaomqcunha** [comment]
Hi @azachar, sorry for that but I couldn't see the comment on my view but I've just renamed the function to "isASuiteToCheck"! 👍

**Comment by azachar** [comment]
Hey @joaomqcunha, 

it is squished+merged now, have a look at the next release 0.6.0.

Thank you once again for your contribution.

Cheers,
Andrej

**Pull request merged**
